spring:
  application:
    name: spring-rag-ai-open-ai
  datasource:
    url: jdbc:postgresql://localhost:5432/ragopenai
    username: admin
    password: password
  ai:
    openai:
      api-key: sk-a_ORg3HB2XMfXv2RLfcVjWFp-TsCPHVAyOjjx_tBAUT3BlbkFJ_5LtFAB5hPyjsHFQTHLpg_YWM9e8Fkl9r2uaZlmPYA
      chat:
        options:
            model: gpt-4o
server:
  port: 8080



  vectorstore:
    pgvector:
    index-type: HNSW
    distance-type: COSINE_DISTANCE
    dimension: 1536
  docker:
    compose:
      lifecycle-management: start_only


